### ISSUE TITLE
Template selector mismatch in code kills app

### ISSUE THREAD

**Issue by kjeremy** [MvvmCross/MvvmCross-AndroidSupport#244]
My application is crashing with a `MvxRecyclerView`.  It throws a null reference expection from https://github.com/MvvmCross/MvvmCross-AndroidSupport/blob/e180ca5e5739c165658135b14a329d2707a60e5c/MvvmCross.Droid.Support.V7.RecyclerView/AttributeHelpers/MvxRecyclerViewAttributeExtensions.cs#L87

Because of this the `MvxLayoutInflater` falls back to the traditional methods of inflation and then dies since we can't inflate the view.

The code is trying to find `"MvxRecyclerView_MvxItemTemplateSelector"` but https://github.com/MvvmCross/MvvmCross-AndroidSupport/blob/master/MvvmCross.Droid.Support.V7.RecyclerView/Resources/values/MvxRecyclerViewBindingAttributes.xml#L4 only has `MvxTemplateSelector`.

I can workaround this issue by including the following in my app:

``` xml
<?xml version="1.0" encoding="utf-8" ?>
<resources>
  <declare-styleable name="MvxRecyclerView">
    <attr name="MvxItemTemplateSelector" format="string" />
  </declare-styleable>
</resources>
```

I'm not sure which value is the intended one.

**Comment by martijn00** [comment]
I think https://github.com/MvvmCross/MvvmCross-AndroidSupport/blob/e180ca5e5739c165658135b14a329d2707a60e5c/MvvmCross.Droid.Support.V7.RecyclerView/AttributeHelpers/MvxRecyclerViewAttributeExtensions.cs#L87 should be changed to `MvxRecyclerView_MvxTemplateSelector` because this was renamed to match MvvmCross naming conventions: https://github.com/MvvmCross/MvvmCross-AndroidSupport/blob/master/MvvmCross.Droid.Support.V7.RecyclerView/ItemTemplates/MvxTemplateSelector.cs
