### ISSUE TITLE
MvxListView in Xml is being cast to MvxAppCompatListView

### ISSUE THREAD

**Issue by CSkoubo** [MvvmCross/MvvmCross-AndroidSupport#257]
When using AppCompat, If you have defined a `MvxListView` in XML and you try to do `FindViewById<MvxListView>(...)` it will crash with the following exception:

`Unable to convert instance of type 'MvvmCross.Droid.Support.V7.AppCompat.Widget.MvxAppCompatListView' to type 'MvvmCross.Binding.Droid.Views.MvxListView'.`

**Sample app:**
https://bitbucket.org/camask/mvxlistview-cast-crash/src/b3bc049462c2aac8089f308fdc1a56741a2d9e3c/Samples/Example.Droid/Fragments/RecyclerViewFragment.cs?at=master&fileviewer=file-view-default

It seems Mvx will Cast non AppCompat widgets to AppCompat ones:

https://github.com/MvvmCross/MvvmCross-AndroidSupport/blob/master/MvvmCross.Droid.Support.V7.AppCompat/MvxAppCompatActivityHelper.cs

This was rather a breaking change for us. I've known this bug for a while, as it was in Alpha channel. But it now occurs in the stable channel of XS. I do not know why this happens now and not with the old stable XS.

I think it would be a good idea to add some information about this.

**Comment by kjeremy** [comment]
What do you mean by you've "known this bug for a while"?  Is this crashing because of a Xamarin upgrade or has it always failed?

A demo project would be awesome.

The rationale behind the `MvxAppCompatActivityHelper` class is that when using `AppCompatActivity` the android support libraries [swap out some classes](https://github.com/android/platform_frameworks_support/blob/62eb3105e51335cf9074a5506d8d2b220aeb95dc/v7/appcompat/src/android/support/v7/app/AppCompatViewInflater.java#L90-L130)  for their tint-aware `AppCompat` versions.  For those views/widgets where we provide `Mvx` versions we need to do the same thing.

That said I'm trying to understand why I added a version of `ListViewCompat` since it is **not** tint-aware and should probably be it's own class.

**Comment by CSkoubo** [comment]
I made a quick sample here:

https://bitbucket.org/camask/mvxlistview-cast-crash/src/b3bc049462c2aac8089f308fdc1a56741a2d9e3c/Samples/Example.Droid/Fragments/RecyclerViewFragment.cs?at=master&fileviewer=file-view-default

If you run this in the latest stable (Cycle 7) it will crash. But if you run it in the stable before that, it will not crash.

(I will try to add some more details, version numbers etc. But currently in a bit of a hurry :) )

Besides i do not see this is a bug, but more of something you should be aware of when developing.

**Comment by kjeremy** [comment]
If it worked in Cycle 6 wouldn't it be a Xamarin bug?

**Comment by Cheesebaron** [comment]
But then again, doesn't it make sense. If you add MvxListView to an AXML file and the framework substitutes it behind your back to a MvxAppCompatListView, which does not itself inherit from MvxListView. Then the cast will break.

**Comment by kjeremy** [comment]
Yeah... so why the heck did it work before?  I think I'll go ahead and remove the swap since it's the wrong thing to do.
